services:
  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - TZ=America/New_York
      - F2B_DB_PURGE_AGE=7d
    volumes:
      - /home/<user>/docker/fail2ban/data:/data
      - /home/<user>/docker/Jellyfin/log:/jellyfin-log:ro
